
module.exports = {
    APP_STATUS_ON:1,
    APP_STATUS_OFF:0,
    RUNNER_WORK_FULL_TIME:1,
    RUNNER_WORK_PART_TIME:0,
    RUNNER_BUSY:1,
    RUNNER_FREE:0,
    ACCOUNT_ACTIVE:1,
    ACCOUNT_INACTIVE:0,
    ORDER_UNASSIGNED:0,
    ORDER_ASSIGNED:1,
    ORDER_COMPLETED:2,
    WORKING:1,
    RESIGNED:0,
    RUNNER_REJECTED_TASK:0,
    RUNNER_ACCEPTED_TASK:1
}
